Readme update
OpenLightingProject/rp2040-dmxsun pull request #34
Opened 2022-01-08 21:40 UTC by kripton

I've finally managed to bring the Readme to a state that the current state of the code and hardware design files deserves :)

Since English is not my native language, I'd be happy about a review. Codespell is happy but I prefer humans to give their opinions.

2022-01-08 21:42 UTC, kripton commented
Oh and as you see, I've decided on a new name since "rp2040-donlge" was a bit thin and didn't explain what the dongle does. rp2040-dmxsund might also not explain the purpose but it is at least distinguishable and memorable. The icon already supports this: https://github.com/OpenLightingProject/rp2040-dongle/blob/main/gfx/favicon.png. But of course, I'm open for proposals here as well.

2022-01-10 22:35 UTC, peternewman commented
> Oh and as you see, I've decided on a new name since "rp2040-donlge" was a bit thin and didn't explain what the dongle does. rp2040-dmxsun might also not explain the purpose but it is at least distinguishable and memorable. The icon already supports this: https://github.com/OpenLightingProject/rp2040-dongle/blob/main/gfx/favicon.png. But of course, I'm open for proposals here as well.

It's also easily backronymable, DMX Sixteen UNiverses :laughing: !

2022-01-10 22:59 UTC, peternewman requested changes
Looks good, mostly minor tidying!

2022-01-10 22:59 UTC, peternewman commented on README.md
> +# rp2040-dmxsun: A USB-DMX-device based on RaspberryPi's RP2040 microcontroller with modular hardware
I think these hyphens would be more standard:
```suggestion
# rp2040-dmxsun: A USB-DMX device based on RaspberryPi's RP2040 micro-controller with modular hardware
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +The rp2040-dmxsun is a multi-purpose DMX-512-A toolbox to control stage lighting systems. It's most common use-case is to transmit the DMX data generated on a PC, RaspberryPi or similar in a format t
```suggestion
The rp2040-dmxsun is a multi-purpose DMX-512-A toolbox to control stage lighting systems. It's most common use-case is to transmit the DMX data generated on a PC, Raspberry Pi or similar in a format that the lighting fixtures on stage can understand. In the most simple case, it's an USB-DMX interface.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +DMX-512-A works in groups called universes and each universe can contain up to 512 channels. dmxsun can transmit up to 16 universes, meaning you can control 8192 channels of DMX data at the same time
Pedant, I think the official naming is slots rather than channels, but the latter is probably better known by most people.

2022-01-10 22:59 UTC, peternewman commented on README.md
> +To the computer, the dmxsun device looks like a network card (it uses the CDC NCM interface) and the integrated DHCP-server assigns an IP-address to the host machine so they can talk to each other.
Is there actually a DHCP server? Isn't it just using zeroconf, which is more of a standard than a server?

2022-01-10 22:59 UTC, peternewman commented on README.md
> +To find out dmxsun's IP address, have a look at your kernel log on Linux (run `dmesg`) or hover over the `Disconnect USB device` icon in Window's task bar or check the network device properties on ma
You should add Avahi/Bonjour support to avoid needing to do this!

2022-01-10 22:59 UTC, peternewman commented on README.md
> +Maybe it's also because outdoor light technicians absolutely love the sun since they can perfectly set up their light show while the sun is shining bright ;)
```suggestion
Maybe it's also because outdoor lighting technicians absolutely love the sun since they can perfectly set up their light show while the sun is shining bright ;)
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +The hardware consists of a base board into which the RaspberryPi Pico-board plugs in to. To get a quick overview of the board's status, 8 RGB status LEDs are attached to the base board.
```suggestion
The hardware consists of a base board into which the Raspberry Pi Pico-board plugs in to. To get a quick overview of the board's status, 8 RGB status LEDs are attached to the base board.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +![3D rendering of base board + 4 IO boards](https://user-images.githubusercontent.com/823537/112302789-c18d1400-8c9b-11eb-99d2-b17a0b3cfb81.png)
Do these renders not get pushed back to the repo, so you could use the raw versions?

2022-01-10 22:59 UTC, peternewman commented on README.md
> +The complete configuration of the device, including IP addresses, patchings, wireless configuration can be stored on each of the IO boards or on the base board.
Is there really more than one IP (does it actually store the PC side one)? Also patching singular. I'd say any unless it writes it to all of them.
```suggestion
The complete configuration of the device, including IP address, patching and wireless configuration can be stored on any of the IO boards or on the base board.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +The status LEDs on the base board indicate which IO board has a valid configuration and which configuration is currently active.
If they may show multiple valid but inactive configs:
```suggestion
The status LEDs on the base board indicate which IO boards have a valid configuration and which configuration is currently active.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +All configurations can be managed via the integrated web server.
This may be better if you mean which preset is used:
```suggestion
All the configurations can be managed via the integrated web server.
```

Or this if you mean all the settings can be set online:
```suggestion
All configuration can be managed via the integrated web server.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +* Find out the dmxsun's IP address as described in the `What is it?`-section
You can link within the Markdown!

2022-01-10 22:59 UTC, peternewman commented on README.md
> +* If you're curious and have such devices, connect a logic analyzer or RS-485-drivers to the GPIOs 6 to 21. Those are the pins where the DMX data comes out. If you attach an RS-485-driver to one of t
Are we aiming for US or British spelling? :laughing: 
```suggestion
* If you're curious and have such devices, connect a logic analyzer or RS-485 driver to GPIOs 6 to 21. Those are the pins where the DMX data comes out. If you attach an RS-485-driver to one of those, you can also attach and control real fixtures.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +Since this is a project that adheres to the guidelines set by RaspberryPi for its pico-sdk (hopefully), you best make sure to follow the detailed documentation at https://datasheets.raspberrypi.com/p
The existing was rather strict, follow this documentation or else!
```suggestion
Since this is a project that adheres to the guidelines set by Raspberry Pi for its pico-sdk (hopefully), you are best off following the detailed documentation at https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +The build process will also build the React App for the integrated Web UI. For this to work, you will need to have NodeJS 14+ and NPM installed. React and all other JavaScript dependencies will be do
I think:
```suggestion
The build process will also build the React App for the integrated Web UI. For this to work, you will need to have NodeJS 14+ and NPM installed. React and all other JavaScript dependencies will be downloaded during the build, so make sure you are connected to the Internet.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +Basically with all dependencies installed, the following steps should suffice:
```suggestion
With all dependencies installed, the following steps should suffice:
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +make -j4
The -j4 won't help on something with fewer cores and may be worse...

2022-01-10 22:59 UTC, peternewman commented on README.md
> +This should result in an `.uf2`-file being generated that you can flash to your Pico-board as described in RaspberryPi's documentation.
```suggestion
This should result in an `.uf2`-file being generated that you can flash to your Pico-board as described in Raspberry Pi's documentation.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +Dmxsun uses a pretty flexible architecture, consisting of mainly 24 DMX buffers acting as the main data storage. Data can come in via USB (either via the emulated Ethernet or some other, emulated pro
You could probably drop the quotes around patching too.
```suggestion
Dmxsun uses a pretty flexible architecture, consisting of mainly 24 DMX buffers acting as the main data storage. Data can come in via USB (either via the emulated Ethernet or some other, emulated protocol), wirelessly via the nRF24 module or from one input port and is then, depending on "patching" stored in one or more DMX buffers.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +From there, again depending on "patching", the data is given to one or more of the local DMX ports, to the nRF24 wireless module or to the host PC via ArtNet or E1.31/sACN.
I think Art-Net is hyphenated...
```suggestion
From there, again depending on "patching", the data is sent to one or more of the local DMX ports, to the nRF24 wireless module or to the host PC via Art-Net or E1.31/sACN.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +Since the hardware is modular, we do have the option to also support DMX input (currently Work-in-progress) or universes with RDM support. There would also be the possibility to drive up to 6 WS2812b
```suggestion
Since the hardware is modular, we do have the option to also support DMX input (currently work-in-progress) or universes with RDM support. There would also be the possibility to drive up to 6 WS2812b-based LED-strings instead of conventional DMX-512-A right off the board.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +For the wireless part, mesh support is planned so you can add additional nodes forwarding the data when the wireless range should not be sufficient. It would also be great if we could talk to other,
```suggestion
For the wireless part, mesh support is planned so you can add additional nodes forwarding the data when the wireless range is insufficient. It would also be great if we could talk to other, existing wireless DMX systems.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +What might also help to make it easier to use is if dmxsun could emulate other, existing USB DMX dongles. Then, it could also be used with other software that is not able to send ArtNet or E1.31/sACN
```suggestion
What might also help to make it easier to use is if dmxsun could emulate other, existing, USB DMX dongles. Then, it could also be used with other software that is not able to send Art-Net or E1.31/sACN but supports other dongles. The disadvantage here is that only a few dongles support more than 4 universes, while dmxsun supports 16.
```

2022-01-10 22:59 UTC, peternewman commented on README.md
> +* libb64 (https://github.com/open-source-parsers/jsoncpp, Public domain)
Link!

2022-01-10 22:59 UTC, peternewman commented on README.md
> +If you attach an nRF24-board, you yourself are responsible to make sure you don't violate any local laws or regulations. Not all channels and transmit powers that the nRF24 module can send on might b
```suggestion
If you attach an nRF24-board, you yourself are responsible to make sure you don't violate any local laws or regulations. Not all channels and transmit powers that the nRF24 module can use may be allowed to be used in your area. The Open Lighting Project cannot be held responsible should you break the law by using this project's hardware and/or software.
```

2022-01-11 18:36 UTC, kripton commented on README.md
> +DMX-512-A works in groups called universes and each universe can contain up to 512 channels. dmxsun can transmit up to 16 universes, meaning you can control 8192 channels of DMX data at the same time
Please be pedantic :) If we do have a standard that uses some specific wording, we should stick to that here as well. In the source code, I might have used "frame" (for a complete DMX packet) and that's not actually in the standard as well.

2022-01-11 18:47 UTC, kripton commented on README.md
> +To the computer, the dmxsun device looks like a network card (it uses the CDC NCM interface) and the integrated DHCP-server assigns an IP-address to the host machine so they can talk to each other.
It indeed is a real DHCP server running on the device and proposing one IP address if asked for one (which is the standard behaviour of most OSes when they detect previously un-known network devices).
The [lwIP stack](https://savannah.nongnu.org/projects/lwip/) that is used also supports "AutoIP" as a form of zeroconf. I had a quick look but found DHCP to be more "reliable". Some OSes might treat network connections as non-functional if their DHCP-requests stay unanswered.
However, I agree that some form of unsolicited service announcement (or mDNS) might help. And I should re-try the AutoIP to check if it works everywhere and makes things easier in the end.

2022-01-11 18:48 UTC, kripton commented on README.md
> +To find out dmxsun's IP address, have a look at your kernel log on Linux (run `dmesg`) or hover over the `Disconnect USB device` icon in Window's task bar or check the network device properties on ma
True, mDNS seems to be the way of choice here.
However, the host name the device announces to the host should have some "random ID" in it so there is no problem when more than one device is connected.

2022-01-11 18:53 UTC, kripton commented on README.md
> +To the computer, the dmxsun device looks like a network card (it uses the CDC NCM interface) and the integrated DHCP-server assigns an IP-address to the host machine so they can talk to each other.
See #40

2022-01-11 18:53 UTC, kripton commented on README.md
> +To find out dmxsun's IP address, have a look at your kernel log on Linux (run `dmesg`) or hover over the `Disconnect USB device` icon in Window's task bar or check the network device properties on ma
See #40

2022-01-11 18:55 UTC, kripton commented on README.md
> +![3D rendering of base board + 4 IO boards](https://user-images.githubusercontent.com/823537/112302789-c18d1400-8c9b-11eb-99d2-b17a0b3cfb81.png)
You mean via the KiCad-Exporter / KiBot-actions? Those currently create a zip-file that can be downloaded but they don't actively push anything to the repo. Even then, the camera angle and the specific combination of the base and the 4 IO boards is not done easily programmatically. I just used the GitHub-hosted images from the discussion pages.

2022-01-11 18:56 UTC, kripton commented on README.md
> +The complete configuration of the device, including IP addresses, patchings, wireless configuration can be stored on each of the IO boards or on the base board.
True, the host's IP is not actually stored, it's just the device's IP minus 1.

2022-01-11 18:59 UTC, kripton commented on README.md
> +The status LEDs on the base board indicate which IO board has a valid configuration and which configuration is currently active.
It does :) Status LEDs for the IO boards display red if not IO board is connected to that slot, yellow if communication is successful but the config is invalid, green if the config is valid but hasn't been loaded and blue if the config is valid and is in use

2022-01-11 19:03 UTC, kripton commented on README.md
> +* Find out the dmxsun's IP address as described in the `What is it?`-section
True, but I've never used intra-document links before. I'll make it a link

2022-01-11 19:03 UTC, kripton commented on README.md
> +* If you're curious and have such devices, connect a logic analyzer or RS-485-drivers to the GPIOs 6 to 21. Those are the pins where the DMX data comes out. If you attach an RS-485-driver to one of t
Phew, no preference here. Since the E1.11 is an US-standard I'd say US? ;)

2022-01-11 19:06 UTC, kripton commented on README.md
> +make -j4
True. and those instructions are also pretty Linux-specific. I thought the `-j4` was quite conservative already but how about `make -j$(($(nproc)+1))`?

2022-01-11 19:07 UTC, kripton commented on README.md
> +* libb64 (https://github.com/open-source-parsers/jsoncpp, Public domain)
Will do. Personally, I actually prefer to see the URLs without the need to hover over them and GitHub makes them links automatically anyways

2022-01-11 19:29 UTC, kripton commented
> It's also easily backronymable, DMX Sixteen UNiverses laughing !

Nice one, didn't even think of it! Want it in the Readme? ;)

2022-01-11 23:08 UTC, peternewman commented on README.md
> +make -j4
What's the time difference between zero and 4? Your suggestion feels it risks some incompatibility; I wonder if -j4 with a note might be a good compromise.

Conservative unless you're on some Pis...

2022-01-12 18:17 UTC, peternewman commented on README.md
> +* Find out the dmxsun's IP address as described in the `What is it?`-section
I think you can just do a #/anchor.

2022-01-12 18:18 UTC, peternewman commented on README.md
> +To find out dmxsun's IP address, have a look at your kernel log on Linux (run `dmesg`) or hover over the `Disconnect USB device` icon in Window's task bar or check the network device properties on ma
Perhaps part of the MAC?

2022-01-12 18:20 UTC, peternewman commented on README.md
> +* Find out the dmxsun's IP address as described in the `What is it?`-section
You have!

2022-01-12 21:43 UTC, kripton commented on README.md
> +To find out dmxsun's IP address, have a look at your kernel log on Linux (run `dmesg`) or hover over the `Disconnect USB device` icon in Window's task bar or check the network device properties on ma
Well, the "MAC address" is also a pretty fake one: https://github.com/OpenLightingProject/rp2040-dongle/blob/f5f1d511b9f2d2f3d519904ce44945ea090ec4ae/src/tusb_lwip_glue.c#L42
But here again, I'd stick to the same approach as we currently do: Use one byte of the "unique board ID"

2022-01-12 21:58 UTC, kripton commented on README.md
> +make -j4
I never heard of "make -j0" before. It would be great if make would do some core-count-based magic here, but it doesn't. The default value without -j parameter is 1. "make -j1" runs one gcc process at a time, -j4 runs 4. On my dated 4-core laptop:
```
make -j1 (default, no parameter):
real    0m35,772s

make -j4 (nproc):
real    0m14,676s

make -j5 (nproc + 1):
real    0m14,689s

make -j64 (deliberately overloading the system):
real    0m13,488s

make -j256 (you never know):
real    0m12,913s
```

So, I don't mind leaving the `-j4` away. People experienced in running make will know a good value for the parameter on their machines and will add it by themselves. Anybody else will have to wait a tad longer ...

The only thing that can give you pain with higher values for `-j` is limited memory or swapping. That can bring down any system to its knees.

2022-01-13 12:39 UTC, peternewman commented on README.md
> +To find out dmxsun's IP address, have a look at your kernel log on Linux (run `dmesg`) or hover over the `Disconnect USB device` icon in Window's task bar or check the network device properties on ma
Ah I didn't realise, yeah that should use part of the unique ID. I'd assumed something like that was already built into the library!

2022-01-18 22:22 UTC, merged